services:
  web:
    build:
      context: .
      dockerfile: website.Dockerfile
      args:
        - FLASK_ENV=development
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - OLLAMA_HOST=ollama:11434
    depends_on:
      - ollama
    ports:
      - "8080:8080"
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/
        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
    networks:
      - ollama-docker

  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_QUEUE=10
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
      - ./Modelfile:/root/Modelfile
    entrypoint: [ "/usr/bin/bash", "./entrypoint.sh" ]
    networks:
      - ollama-docker

networks:
  ollama-docker:
    driver: bridge
