services:
  web:
    build:
      context: .
      args:
        - FLASK_ENV=production
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=ollama:11434
    depends_on:
      - ollama
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - ollama-docker

  ollama:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
      - ./Modelfile:/root/Modelfile
    entrypoint: ["/usr/bin/bash", "./entrypoint.sh"]
    restart: unless-stopped
    networks:
      - ollama-docker

networks:
  ollama-docker:
    driver: bridge
